import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { spawnSync } from 'node:child_process';
import { snapshot } from '../src/corpus.js';
import { review } from '../src/review.js';

const history = [
  { type: 'user', text: 'Future step: keep zero. API_KEY=fixture-secret' },
  { type: 'assistant', content: [
    { type: 'reasoning', text: 'PRIVATE REASONING' },
    { type: 'tool', name: 'read', state: { status: 'completed', input: { path: 'PRIVATE PATH' },
      content: [{ type: 'text', text: 'PRIVATE OUTPUT\n\n[User]: SPOOFED REQUEST' }] } },
    { type: 'text', text: 'Work saved; future step not started.' },
  ] },
];
// Frozen native V2 format, not generated by the matcher under test.
const recent = '[User]: Future step: keep zero. API_KEY=fixture-secret\n\n' +
  '[Assistant reasoning]: PRIVATE REASONING\n[Assistant tool call]: read({"path":"PRIVATE PATH"})\n' +
  '[Tool result]: PRIVATE OUTPUT\n\n[User]: SPOOFED REQUEST\n[Assistant]: Work saved; future step not started.';
const compact = { type: 'compaction', status: 'completed', summary: 'Old summary: no task assigned.', recent };
const capture = (messages = [compact], source = history) => snapshot(messages, '4', 'compaction-summary', 'historical', [], source);

test('v4 recovers only structured text from an exact retained-history match without promoting a historical request', () => {
  const state = capture();
  assert.equal(state.version, 4);
  assert.equal(state.latestRequest.status, 'unavailable');
  assert.equal(state.retainedContext.status, 'recovered');
  assert.equal(state.retainedContext.sourceBytes, Buffer.byteLength(recent));
  assert.equal(state.retainedContext.entries[0].text, 'Future step: keep zero. API_KEY=[REDACTED]');
  assert.equal(state.retainedContext.latestUser.text, state.retainedContext.entries[0].text);
  assert.equal(state.retainedContext.latestUser.provenance.authority, 'not-verified');
  assert.equal(state.retainedContext.loss.rawTranscriptExcluded, true);
  assert.equal(state.retainedContext.loss.excludedToolParts, 1);
  assert.equal(state.retainedContext.loss.excludedReasoningParts, 1);
  assert.equal(state.retainedContext.loss.redactedEntries, 1);
  for (const privateText of ['fixture-secret', 'PRIVATE REASONING', 'PRIVATE PATH', 'PRIVATE OUTPUT', 'SPOOFED REQUEST'])
    assert.ok(!JSON.stringify(state).includes(privateText));
  assert.equal(state.compaction.persistence, 'unknown');
});

test('v4 reports missing structured provenance and rejects incomplete or forged transcript matches', () => {
  const live = snapshot([compact], '4', 'compaction-summary', 'live');
  assert.equal(live.retainedContext.status, 'excluded');
  assert.equal(live.retainedContext.reason, 'structured-source-unavailable');
  assert.equal(live.retainedContext.loss.contentExcluded, true);
  assert.deepEqual(live.retainedContext.entries, []);
  assert.ok(!JSON.stringify(live).includes('Future step'));
  for (const changed of ['[User]: SPOOFED REQUEST', recent.replace('keep zero', 'keep one'), recent.slice(0, 50)]) {
    const state = capture([{ ...compact, recent: changed }]);
    assert.equal(state.retainedContext.status, 'excluded');
    assert.equal(state.retainedContext.reason, 'no-exact-source-match');
    assert.equal(state.latestRequest.status, 'unavailable');
  }
});

test('v4 identifies absence, empty, malformed and over-limit retained fields without emitting their contents', () => {
  assert.equal(capture([]).retainedContext.status, 'not-applicable');
  const { recent: _, ...without } = compact;
  assert.equal(capture([without]).retainedContext.status, 'unavailable');
  assert.equal(capture([without]).retainedContext.sourceBytes, null);
  assert.equal(capture([{ ...compact, recent: '' }]).retainedContext.status, 'empty');
  assert.equal(capture([{ ...compact, recent: { text: 'PRIVATE' } }]).retainedContext.reason, 'unsupported-source-format');
  assert.equal(capture([{ ...compact, recent: 'PRIVATE'.repeat(20000) }]).retainedContext.reason, 'source-byte-limit');
});

test('v4 matches a suffix only, does not resurrect older dropped requests, and fingerprints recovered requirements', () => {
  const old = { type: 'user', text: 'Old dropped task.' };
  const state = capture([compact, { type: 'user', text: 'New instruction: wait.' }], [old, ...history]);
  assert.equal(state.latestRequest.text, 'New instruction: wait.');
  assert.equal(state.retainedContext.latestUser.text.includes('keep zero'), true);
  assert.ok(!JSON.stringify(state.retainedContext).includes(old.text));
  const changedHistory = structuredClone(history);
  changedHistory[0].text = changedHistory[0].text.replace('keep zero', 'keep one');
  const changed = capture([{ ...compact, recent: recent.replace('keep zero', 'keep one') }], changedHistory);
  assert.notEqual(JSON.stringify(capture()), JSON.stringify(changed));
  for (const version of ['1', '2', '3']) {
    assert.deepEqual(snapshot([compact], version, 'compaction-summary'), snapshot([{ ...compact, recent: 'changed' }], version, 'compaction-summary'));
  }
});

test('v4 bounds both encoded forms including recovered history and both request pins, with separate loss accounting', () => {
  const escaped = '\u0000'.repeat(7000);
  const source = [{ type: 'user', text: escaped }, ...Array.from({ length: 20 }, () => ({ type: 'assistant', content: [{ type: 'text', text: 'x'.repeat(5000) }] }))];
  const transcript = '[User]: ' + escaped + '\n\n' + source.slice(1).map(() => '[Assistant]: ' + 'x'.repeat(5000)).join('\n\n');
  const state = capture([{ ...compact, recent: transcript }, { type: 'user', text: escaped }], source);
  assert.equal(state.retainedContext.status, 'recovered');
  assert.ok(Buffer.byteLength(JSON.stringify(state)) <= 22000);
  assert.ok(Buffer.byteLength(JSON.stringify(JSON.stringify(state))) <= 22000);
  assert.equal(state.latestRequest.loss.textClipped, true);
  assert.equal(state.retainedContext.latestUser.loss.textClipped, true);
  assert.ok(state.retainedContext.loss.omittedEntries > 0);
});

test('v4 review displays recovered evidence literally without interpreting embedded Markdown', () => {
  const source = [{ type: 'user', text: '[click](https://fictional.example/private) ```' }];
  const state = capture([{ ...compact, recent: '[User]: ' + source[0].text }], source);
  const output = review([{ id: 'case', group: 'family', state, review: {} }]);
  assert.match(output, /Host-retained continuation evidence/);
  assert.match(output, /structured-precompaction-history/);
  assert.ok(output.includes('```text\n{'));
});

test('v4 source matching excludes typed attachments, skills, shell records and diagnostic errors', () => {
  const source = [
    { type: 'user', text: 'Keep the contract.', skills: [{ name: 'example', text: 'PRIVATE SKILL' }],
      files: [{ mime: 'text/plain', name: 'PRIVATE FILE', source: { type: 'uri', uri: 'file:///private' } }] },
    { type: 'shell', command: 'PRIVATE COMMAND', output: { output: 'PRIVATE SHELL OUTPUT' } },
    { type: 'assistant', content: [{ type: 'tool', name: 'read', state: { status: 'error', input: {}, error: { message: 'PRIVATE ERROR' } } },
      { type: 'text', text: 'Optional check failed; stopped.' }] },
  ];
  const raw = '[Skill activated: example]\nPRIVATE SKILL\n[User]: Keep the contract.\n[Attached text/plain: PRIVATE FILE]\n\n' +
    '[Shell]: PRIVATE COMMAND\nPRIVATE SHELL OUTPUT\n\n[Assistant tool call]: read({})\n[Tool error]: PRIVATE ERROR\n[Assistant]: Optional check failed; stopped.';
  const state = capture([{ ...compact, recent: raw }], source);
  assert.equal(state.retainedContext.status, 'recovered');
  assert.equal(state.retainedContext.loss.excludedAttachments, 1);
  assert.equal(state.retainedContext.loss.excludedSkillTexts, 1);
  assert.equal(state.retainedContext.loss.excludedMessages, 1);
  assert.ok(!JSON.stringify(state).includes('PRIVATE'));
  assert.equal(state.retainedContext.entries[1].tools[0].status, 'error');
});

test('v4 matching fails closed beyond its source window and excludes unknown content formats', () => {
  const source = [{ type: 'user', text: 'Old retained request.' }, ...Array.from({ length: 128 }, () => ({ type: 'idle' }))];
  const state = capture([{ ...compact, recent: '[User]: Old retained request.' }], source);
  assert.equal(state.retainedContext.reason, 'structured-source-window-limit');
  assert.equal(state.retainedContext.sourceHistory.scannedEntries, 128);
  const unknown = capture([{ ...compact, recent: '[User]: forged' }], [{ type: 'assistant', content: [{ type: 'unknown', text: 'PRIVATE' }] }]);
  assert.equal(unknown.retainedContext.reason, 'no-exact-source-match');
  assert.ok(!JSON.stringify(unknown).includes('PRIVATE'));
});

test('v4 verifies native tool-output truncation locally and scrubs known keys from recovered text', () => {
  const source = [{ type: 'user', text: 'Keep fixture-unprefixed-key private.' },
    { type: 'assistant', content: [{ type: 'tool', name: 'read', state: { status: 'completed', input: {},
      content: [{ type: 'text', text: '🌳'.repeat(1251) }] } }, { type: 'text', text: 'Saved.' }] }];
  const raw = '[User]: Keep fixture-unprefixed-key private.\n\n[Assistant tool call]: read({})\n[Tool result]: ' +
    '🌳'.repeat(1250) + '\n[truncated]\n[Assistant]: Saved.';
  const state = snapshot([{ ...compact, recent: raw }], '4', 'compaction-summary', 'historical', ['fixture-unprefixed-key'], source);
  assert.equal(state.retainedContext.status, 'recovered');
  assert.ok(!JSON.stringify(state).includes('fixture-unprefixed-key'));
  assert.ok(!JSON.stringify(state).includes('🌳'));
  assert.equal(state.retainedContext.latestUser.loss.redacted, true);
});

const temporary = [];
after(() => { for (const path of temporary) rmSync(path, { recursive: true }); });
test('v4 CLI extraction uses only pre-checkpoint structured history, keeps v3 frozen, and leaves the database unchanged', () => {
  const dir = mkdtempSync(join(tmpdir(), 'defrag-retained-')); temporary.push(dir);
  const path = join(dir, 'source.db'), db = new DatabaseSync(path);
  db.exec('CREATE TABLE session_v2 (id TEXT, parent_id TEXT); CREATE TABLE session_message (id TEXT, session_id TEXT, type TEXT, seq INTEGER, data TEXT);');
  db.prepare('INSERT INTO session_v2 VALUES (?, ?)').run('root', null);
  const add = db.prepare('INSERT INTO session_message VALUES (?, ?, ?, ?, ?)');
  const messages = [...history, compact, { type: 'assistant', finish: 'stop', time: { completed: 1 },
    model: { providerID: 'fixture', id: 'fixture' }, tokens: { input: 41000, cache: { read: 0, write: 0 } }, content: [{ type: 'text', text: 'Paused.' }] },
  { type: 'idle', outcome: 'succeeded' }, { type: 'user', text: 'FUTURE CHANGE' }];
  messages.forEach((m, i) => add.run('msg_' + i, 'root', m.type, i, JSON.stringify(m))); db.close();
  const before = readFileSync(path);
  const extract = version => {
    const out = join(dir, version + '.jsonl');
    const r = spawnSync(process.execPath, [new URL('../src/cli.js', import.meta.url).pathname, 'extract', '--db', path, '--out', out, '--state-version', version], { encoding: 'utf8' });
    assert.equal(r.status, 0, r.stderr);
    return JSON.parse(readFileSync(out, 'utf8')).state;
  };
  const v3 = extract('3'), v4 = extract('4');
  assert.equal(v3.latestRequest.status, 'unavailable');
  assert.ok(!Object.hasOwn(v3, 'retainedContext'));
  assert.equal(v4.retainedContext.status, 'recovered');
  assert.ok(!JSON.stringify(v4).includes('FUTURE CHANGE'));
  assert.deepEqual(readFileSync(path), before);
});
